%YAML 1.1
---
resolve: commits
owner: jimschubert
repo: labeler
groupings:
  - name: Functionality
    patterns: ['(?i)^new\b', '(?i)^initial\b', '(?i)^support\b', '(?i)^introduce\b', '(?i)^feat\b']
  - name: Fixes
    patterns: ['(?i)^fix\b', '(?i)^bug', '(?i).*fixes$']
  - name: Uncategorized
    patterns: ['.*']
exclude:
  - '^(?i)wip\b'
  - '^(?i)help\b'
  - '^(?i)doc\b'
  - '^(?i)docs\b'
  - '^(?i)test\b'
  - '^(?i)trying\b'
  - '^(?i)workflow\b'
  - '^(?i)update readme\b'
  - '^(?i)style\b'
  - '^(?i)chore\b'
sort: asc
max_commits: 250
local: false